export const Quotes = [
    "\"Believe you can, and you're halfway there.\" - Theodore Roosevelt",
    "\"I avoid looking forward or backward, and try to keep looking upward.\" - Charlotte Brontë",
    "\"I hated every minute of training, but I said, 'Don\'t quit. Suffer now and live the rest of your life as a champion.'\" - Muhammad Ali",
    "\"Our greatest glory is not in never failing, but in rising up every time we fail.\" - Ralph Waldo Emerson",
    "\"Every worthy act is difficult. Ascent is always difficult. Descent is easy and often slippery.\" - Mahatma Gandhi",
    "\"It is by going down into the abyss that we recover the treasures of life. Where you stumble, there lies your treasure.\" - Joseph Campbell",
    "\"The great thing in this world is not so much where you stand as what direction you are moving.\" - Oliver Wendell Holmes",
    "\"I've been absolutely terrified every moment of my life - and I've never let it keep me from doing a single thing I wanted to do.\" - Georgia O'Keeffe",
    "\"If you accept the expectations of others, especially negative ones, then you never will change the outcome.\" - Michael Jordan",
    "\"People often say that motivation doesn't last. Neither does bathing. That's why we recommend it daily.\" - Zig Ziglar",
    "\"Success is the sum of small efforts, repeated day in and day out.\" - Robert Collier",
    "\"Tomorrow is the most important thing in life; it comes to us at midnight very clean. It's perfect when it arrives, and it puts itself in our hands. It hopes we've learned something from yesterday.\" - John Wayne",
    "\"If you can quit for a day, you can quit for a lifetime.\" - Benjamin Alire Sáenz",
    "\"Fall seven times, stand up eight.\" - Japanese proverb",
    "\"Either you run the day, or the day runs you.\" - Jim Rohn",
    "\"Every strike brings me closer to the next home run.\" - Babe Ruth",
    "\"Life is like riding a bicycle. To keep your balance, you must keep moving.\" - Albert Einstein",
    "\"When you rise in the morning, think of what a privilege it is to be alive, to think, to enjoy, to love …\" - Marcus Aurelius",
    "\"Sometimes you can only find Heaven by slowly backing away from Hell.\" - Carrie Fisher",
    "\"Getting sober was one of the the three pivotal events in my life, along with becoming an actor and having a child. Of the three, finding my sobriety was the hardest.\" - Robert Downey Jr.",
    "\"I understood, through rehab, things about creating characters. I understood that creating whole people means knowing where we come from, how we can make a mistake and how we overcome things to make ourselves stronger.\" - Samuel L. Jackson",
    "\"Once I was clear-headed, and I hadn't been clear-headed in so long, I was like, I can never go back. And I'm still thankful.\" - Travis Barker",
    "\"I got sober. I stopped killing myself with alcohol. I began to think: 'Wait a minute - if I can stop doing this, what are the possibilities?' And slowly it dawned on me that it was maybe worth the risk.\" ― Craig Ferguson",
    "\"I realized that I only had two choices: I was either going to die or I was going to live, and which one did I want to do? And then I said those words, 'I'll get help,' or, 'I need help. I'll get help.' And my life turned around. Ridiculous for a human being to take 16 years to say, 'I need help.'\" - Sir Elton John",
    "\"My recovery from drug addiction is the single greatest accomplishment of my life… but it takes work — hard, painful work — but the help is there, in every town and career, drug/drink freed members of society, from every single walk and talk of life to help and guide.\" - Jamie Lee Curtis",
    "\"If it wasn't for that rehab center, I probably wouldn't have been here. In terms of recovery, it has been very important for me to be a part of a recovery community, to actively be around my people because they understand me. They get it.\" - Macklemore",
    "\"Though no one can go back and make a brand new start, anyone can start from now and make a brand new ending.\" - Carl Bard",
    "\"Everyone has inside of him a piece of good news. The good news is that you don't know how great you can be! How much you can love! What you can accomplish! And what your potential is!\" - Anne Frank",
    "\"What progress, you ask, have I made? I have begun to be a friend to myself.\" - Hecato",
    "\"Find the seed at the bottom of your heart and bring forth a flower.\" - Shigenori Kameoka",
    "\"What makes the desert beautiful is that somewhere it hides a well.\" - Antoine de Saint-Exupery",
    "\"All the suffering, stress, and addiction comes from not realizing you already are what you are looking for.\" - Jon Kabat-Zinn",
    "\"People spend a lifetime searching for happiness; looking for peace. They chase idle dreams, addictions, religions, even other people, hoping to fill the emptiness that plagues them. The irony is the only place they ever needed to search was within.\" - Ramona L. Anderson",
    "\"The most common way people give up their power is by thinking they don't have any.\" - Alice Walker",
    "\"Be yourself; everyone else is already taken.\" - Oscar Wild",
    "\"It always seems impossible until it's done.\" - Nelson Mandela",
    "\"In the midst of winter, I found there was, within me, an invincible summer. And that makes me happy. For it says that no matter how hard the world pushes against me, within me, there's something stronger — something better, pushing right back.\" - Albert Camus",
    "\"Character cannot be developed in ease and quiet. Only through experience of trial and suffering can the soul be strengthened, ambition inspired, and success achieved.\" - Helen Keller",
    "\"We may think there is willpower involved, but more likely … change is due to want power. Wanting the new addiction more than the old one. Wanting the new me in preference to the person I am now.\" - George Sheehan",
    "\"Man never made any material as resilient as the human spirit.\" - Bernard Williams",
    "\"You can come out of the furnace of trouble two ways: if you let it consume you, you come out a cinder; but there is a kind of metal which refuses to be consumed, and comes out a star.\" - Jean Church",
    "\"I have learned over the years that when one's mind is made up, this diminishes fear.\" - Rosa Parks",
    "\"Hardships often prepare ordinary people for an extraordinary destiny.\" - C.S. Lewis",
    "\"Sometimes we motivate ourselves by thinking of what we want to become. Sometimes we motivate ourselves by thinking about who we don't ever want to be again.\" - Shane Niemeyer",
    "\"When we meet real tragedy in life, we can react in two ways - either by losing hope and falling into self-destructive habits, or by using the challenge to find our inner strength. Thanks to the teachings of Buddha, I have been able to take this second way.\" - Dalai Lama",
    "\"Cause sometimes you just feel tired. Feel weak, and when you feel weak, you feel like you wanna just give up. But you gotta search within you. You gotta find that inner strength. And just pull it out of you, and get that motivation to not give up, and not be a quitter, no matter how bad you wanna just fall flat on your face.\" - Eminem",
    "\"Life is not easy for any of us. But what of that? We must have perseverance and, above all, confidence in ourselves. We must believe that we are gifted for something, and that this thing, at whatever cost, must be attained.\" - Marie Curie",
    "\"Life has many ways of testing a person's will, either by having nothing happen at all or by having everything happen all at once.\" - Paulo Coelho",
    "\"Today you are You, that is truer than true. There is no one alive who is Youer than You.\" - Dr. Seuss",
    "\"Nothing is impossible; the word itself says, 'I'm possible!'\" - Audrey Hepburn",
    "\"What lies behind us and what lies before us are tiny matters compared to what lies within us.\" - Ralph Waldo Emerson",
    "\"I can't change the direction of the wind, but I can adjust my sails to always reach my destination.\" - Jimmy Dean",
    "\"I dwell in possibility.\" - Emily Dickinson",
    "\"Don't let the past steal your present.\" - Terri Guillemets",
    "\"Addiction begins with the hope that something 'out there' can instantly fill up the emptiness inside.\" - Jean Kilbourne",
    "\"Hope is a good thing, maybe even the best of things, and good things never die.\" - Stephen King",
    "\"The only journey is the one within.\" - Rainer Maria Rilke",
    "\"Every experience in your life is being orchestrated to teach you something you need to know to move forward.\" - Brian Tracy",
    "\"When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.\" - Henry Ford",
    "\"If things go wrong, don't go with them.\" - Roger Babson",
    "\"Every noble work is at first impossible.\" - Thomas Carlyle",
    "\"Experience is not what happens to you, it is what you do with what happens to you.\" - Aldous Huxley",
    "\"We can't solve problems by using the same kind of thinking we used when we created them.\" - Albert Einstein",
    "\"Whether you think you can or you think you can't, you're right.\" - Henry Ford",
    "\"The only person you are destined to become is the person you decide to be.\" - Ralph Waldo Emerson",
    "\"The best way out is always through.\" - Robert Frost",
    "\"Don't judge each day by the harvest you reap but by the seeds that you plant.\" - Robert Louis Stevenson",
    "\"As one goes through life, one learns that if you don't paddle your own canoe, you don't move.\" - Katharine Hepburn",
    "\"Amazing how we can light tomorrow with today.\" - Elizabeth Barrett Browning",
    "\"When you get into a tight place and everything goes against you, till it seems you could not hang on a minute longer, never give up then, for that is just the place and time that the tide will turn.\" - Harriet Beecher Stowe",
    "\"Keep steadily before you the fact that all true success depends at last upon yourself.\" - Theodore T. Hunger",
    "\"The best time to plant a tree was 20 years ago. The second best time is now.\" - Chinese proverb",
    "\"If we are facing in the right direction, all we have to do is keep on walking.\" - Chinese proverb",
    "\"Patience and the mulberry leaf becomes a silk gown.\" - Chinese proverb",
    "\"Happiness is where we find it, but rarely where we seek it.\" - Chinese proverb",
    "\"Adapt the remedy to the disease.\" - Chinese proverb",
    "\"Control your emotions or they will control you.\" - Chinese proverb",
    "\"A wise man adapts himself to circumstances, as water shapes itself to the vessel that contains it.\" - Chinese proverb",
    "\"With true friends…even water drunk together is sweet enough.\" - Chinese proverb",
    "\"Either do not begin or, having begun, do not give up.\" - Chinese proverb",
    "\"If you want happiness for an hour, take a nap. If you want happiness for a day, go fishing. If you want happiness for a year, inherit a fortune. If you want happiness for a lifetime, help somebody.\" - Chinese proverb",
    "\"It is easy to get a thousand prescriptions but hard to get one single remedy.\" - Chinese proverb",
    "\"First the man takes a drink, then the drink takes a drink, then the drink takes a man.\" - Chinese proverb",
    "\"It is better to take many small steps in the right direction than to make a great leap forward only to stumble backward.\" - Chinese proverb",
    "\"I've wanted to feel pleasure to the point of insanity. They call it getting high, because it's wanting to know that higher level, that godlike level. You want to touch the heavens, you want to feel glory and euphoria, but the trick is it takes work.\" - Anthony Kiedis",
    // "\"Getting sober was one of the three pivotal events in my life, along with becoming an actor and having a child. Of the three, finding my sobriety was the hardest thing.\" - Gary Oldman",
    "\"If you hear a voice within you say 'you cannot paint,' then by all means paint and that voice will be silenced.\" - Vincent Van Gogh",
    "\"I have absolutely no pleasure in the stimulants in which I sometimes so madly indulge. It has not been in the pursuit of pleasure that I have periled life and reputation and reason. It has been the desperate attempt to escape from torturing memories, from a sense of insupportable loneliness and a dread of some strange impending doom.\" - Edgar Allan Poe",
    "\"I've been sober for 18 years now. It wasn't like you flick a switch, and you're sober. It takes a while. You have to learn how to do everything all over again. There is life after addiction, and it's really good. If I had known, I'd have stopped earlier.\" - Joe Walsh",
    "\"I went to hell and back, but I wouldn't have it any other way. Then I wouldn't be in the position I'm in, happy about life and comfortable in my skin.\" - Drew Barrymore",
    "\"A lot of people think that addiction is a choice. A lot of people think it's a matter of will. That has not been my experience. I don't find it to have anything to do with strength.\" - Matthew Perry",
    "\"I think that the power is the principle. The principle of moving forward, as though you have the confidence to move forward, eventually gives you confidence when you look back and see what you've done.\" - Robert Downey Jr.",
    "\"Not feeling is no replacement for reality. Your problems today are still your problems tomorrow.\" - Larry Michael Dredla",
    "\"What is an addiction, really? It is a sign, a signal, a symptom of distress. It is a language that tells us about a plight that must be understood.\" - Alice Miller",
    "\"The greatest mistake you can make in life is to continually be afraid you will make one.\" - Elbert Hubbard",
    "\"Turn your face to the sun and the shadows fall behind you.\" - Charlotte Whitton",
    "\"You must do the things you think you cannot do.\" - Eleanor Roosevelt"
]
